/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import org.neuroph.core.NeuralNetwork;

/**
 *
 * @author JASMIN-SOMA
 */
public class JFDesercionEscolar extends javax.swing.JFrame {
    JDAuto jDAuto = new JDAuto(this, rootPaneCheckingEnabled);
    FrmCreditos frmCreditos= new FrmCreditos();
    /**
     * Creates new form JFDesercionEscolar
     */
    public JFDesercionEscolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbtAA1 = new javax.swing.JRadioButton();
        rbtAA2 = new javax.swing.JRadioButton();
        rbtAA3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbtNoFO = new javax.swing.JRadioButton();
        rbtYesFO = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtNAA1 = new javax.swing.JRadioButton();
        rbtNAA2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbtDeficientEconS = new javax.swing.JRadioButton();
        rbtRegularEconS = new javax.swing.JRadioButton();
        rbtGoodEconS = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbtNAC1 = new javax.swing.JRadioButton();
        rbtNAC2 = new javax.swing.JRadioButton();
        rbtNAC3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbtDeficientF = new javax.swing.JRadioButton();
        rbtRegularF = new javax.swing.JRadioButton();
        rbtGoodF = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rbtDeficientES = new javax.swing.JRadioButton();
        rbtRegularES = new javax.swing.JRadioButton();
        rbtGoodES = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAuto = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("Deserción escolar");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("ACADEMIC AVERAGE:");

        buttonGroup1.add(rbtAA1);
        rbtAA1.setSelected(true);
        rbtAA1.setText("AA>=9.0");

        buttonGroup1.add(rbtAA2);
        rbtAA2.setText("7.5<= AA < 9.0");

        buttonGroup1.add(rbtAA3);
        rbtAA3.setText("AA < 7.5");

        jLabel4.setText("FIRST OPTION:");

        buttonGroup2.add(rbtNoFO);
        rbtNoFO.setSelected(true);
        rbtNoFO.setText("NO");

        buttonGroup2.add(rbtYesFO);
        rbtYesFO.setText("YES");

        jLabel5.setText("NO ACCREDITED ASSIGMENTS:");

        buttonGroup3.add(rbtNAA1);
        rbtNAA1.setSelected(true);
        rbtNAA1.setText("NAA = 0");

        buttonGroup3.add(rbtNAA2);
        rbtNAA2.setText("NAA > 0");

        jLabel6.setText("ECONOMIC STATUS:");

        buttonGroup4.add(rbtDeficientEconS);
        rbtDeficientEconS.setSelected(true);
        rbtDeficientEconS.setText("DEFICIENT");

        buttonGroup4.add(rbtRegularEconS);
        rbtRegularEconS.setText("REGULAR");

        buttonGroup4.add(rbtGoodEconS);
        rbtGoodEconS.setText("GOOD");

        jLabel7.setText("NO ATTENDING CLASS:");

        buttonGroup5.add(rbtNAC1);
        rbtNAC1.setSelected(true);
        rbtNAC1.setText("NAC > 15%");

        buttonGroup5.add(rbtNAC2);
        rbtNAC2.setText("0% < NAC <= 15%");

        buttonGroup5.add(rbtNAC3);
        rbtNAC3.setText("NAC = 0%");

        jLabel8.setText("FITNESS:");

        buttonGroup6.add(rbtDeficientF);
        rbtDeficientF.setSelected(true);
        rbtDeficientF.setText("DEFICIENT");

        buttonGroup6.add(rbtRegularF);
        rbtRegularF.setText("REGULAR");

        buttonGroup6.add(rbtGoodF);
        rbtGoodF.setText("GOOD");

        jLabel9.setText("EMOTIONAL STATUS:");

        buttonGroup7.add(rbtDeficientES);
        rbtDeficientES.setSelected(true);
        rbtDeficientES.setText("DEFICIENT");

        buttonGroup7.add(rbtRegularES);
        rbtRegularES.setText("REGULAR");

        buttonGroup7.add(rbtGoodES);
        rbtGoodES.setText("GOOD");

        jLabel10.setText("RESULTADO:");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAuto.setText("AUTO");
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        btnCreditos.setText("CREDITOS");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(197, 197, 197)
                        .addComponent(txtResultado)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addGap(65, 65, 65)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtAA1)
                                    .addComponent(rbtNoFO)
                                    .addComponent(rbtNAA1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtYesFO)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtAA2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtAA3))
                                    .addComponent(rbtNAA2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(rbtGoodEconS))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtDeficientEconS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtRegularEconS))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtNAC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtNAC2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtNAC3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtDeficientF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtRegularF)
                                .addGap(18, 18, 18)
                                .addComponent(rbtGoodF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtDeficientES)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtRegularES))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(btnAuto)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtGoodES))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(btnCreditos)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtAA1)
                    .addComponent(rbtAA2)
                    .addComponent(rbtAA3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtNoFO)
                    .addComponent(rbtYesFO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtNAA1)
                        .addComponent(rbtNAA2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtDeficientEconS)
                    .addComponent(rbtRegularEconS)
                    .addComponent(rbtGoodEconS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbtNAC1)
                    .addComponent(rbtNAC2)
                    .addComponent(rbtNAC3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbtDeficientF)
                    .addComponent(rbtRegularF)
                    .addComponent(rbtGoodF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtDeficientES)
                    .addComponent(rbtRegularES)
                    .addComponent(rbtGoodES))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(jButton1)
                    .addComponent(btnAuto)
                    .addComponent(btnCreditos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "INSERT NAME.");
        } else {
            // load the saved network 
            NeuralNetwork neuralNetwork = NeuralNetwork.createFromFile("desercionEscolar_multilayer.nnet");

            // set network input
            int AA = -1;
            int FO = 0;
            int NAA = 0;
            int ECS = -1;
            int NAC = -1;
            int F = -1;
            int EMS = -1;

            if (rbtAA1.isSelected()) {
                AA = -1;
            } else if (rbtAA2.isSelected()) {
                AA = 0;
            } else {
                AA = 1;
            }

            if (rbtNoFO.isSelected()) {
                FO = 0;
            } else {
                FO = 1;
            }

            if (rbtNAA1.isSelected()) {
                NAA = 0;
            } else {
                NAA = 1;
            }

            if (rbtDeficientEconS.isSelected()) {
                ECS = -1;
            } else if (rbtRegularEconS.isSelected()) {
                ECS = 0;
            } else if (rbtGoodEconS.isSelected()) {
                ECS = 1;
            }

            if (rbtNAC1.isSelected()) {
                NAC = -1;
            } else if (rbtNAC2.isSelected()) {
                NAC = 0;
            } else if (rbtNAC3.isSelected()) {
                NAC = 1;
            }

            if (rbtDeficientF.isSelected()) {
                F = -1;
            } else if (rbtRegularF.isSelected()) {
                F = 0;
            } else if (rbtGoodF.isSelected()) {
                F = 1;
            }

            if (rbtDeficientES.isSelected()) {
                EMS = -1;
            } else if (rbtRegularES.isSelected()) {
                EMS = 0;
            } else if (rbtGoodES.isSelected()) {
                EMS = 1;
            }

            neuralNetwork.setInput(AA, FO, NAA, ECS, NAC, F, EMS);

            // calculate network 
            neuralNetwork.calculate();

            // get network output 
            double[] networkOutput = neuralNetwork.getOutput();
            int salida1 = (int) (networkOutput[0] + 0.5);

            if (salida1 == 0) {
                txtResultado.setText(txtNombre.getText() + " LOW RISK!!");
            } else {
                txtResultado.setText(txtNombre.getText() + " HIGH RISK!!");
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtResultado.setText("");
        rbtAA1.isSelected();
        rbtNoFO.isSelected();
        rbtNAA1.isSelected();
        rbtDeficientEconS.isSelected();
        rbtNAC1.isSelected();
        rbtDeficientF.isSelected();
        rbtDeficientES.isSelected();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
        jDAuto.setVisible(true);
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        frmCreditos.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDesercionEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDesercionEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDesercionEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDesercionEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDesercionEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCreditos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtAA1;
    private javax.swing.JRadioButton rbtAA2;
    private javax.swing.JRadioButton rbtAA3;
    private javax.swing.JRadioButton rbtDeficientES;
    private javax.swing.JRadioButton rbtDeficientEconS;
    private javax.swing.JRadioButton rbtDeficientF;
    private javax.swing.JRadioButton rbtGoodES;
    private javax.swing.JRadioButton rbtGoodEconS;
    private javax.swing.JRadioButton rbtGoodF;
    private javax.swing.JRadioButton rbtNAA1;
    private javax.swing.JRadioButton rbtNAA2;
    private javax.swing.JRadioButton rbtNAC1;
    private javax.swing.JRadioButton rbtNAC2;
    private javax.swing.JRadioButton rbtNAC3;
    private javax.swing.JRadioButton rbtNoFO;
    private javax.swing.JRadioButton rbtRegularES;
    private javax.swing.JRadioButton rbtRegularEconS;
    private javax.swing.JRadioButton rbtRegularF;
    private javax.swing.JRadioButton rbtYesFO;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables

}
